name: Android CI

on:
  push:
    branches: [ "main" ]
    tags: 
    - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # Required permission to create a GitHub Release
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Decode keystore
      run: |
        echo "$KEYSTORE_BASE64" | base64 --decode > app/xrayfa.jks
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}


      # Dynamically extract exact Go version from go.mod
    - name: Get Exact Go Version from go.mod
      id: go_version
      run: |
        GO_VER=$(awk '/^go /{print $2}' AndroidLibXrayLite/go.mod)
        echo "Extracted Go version: $GO_VER"
        echo "version=$GO_VER" >> $GITHUB_OUTPUT

    - name: Setup Golang
      uses: actions/setup-go@v5.4.0
      with:
        go-version: ${{ steps.go_version.outputs.version }}

    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        export PATH=$PATH:~/go/bin
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: ./gradlew assembleStandardRelease


    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: app/build/outputs/apk/standard/release/*.apk

# Auto-release step
    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/') # Only execute this step if triggered by a tag push
      with:
        files: app/build/outputs/apk/standard/release/*.apk # Directly use the path of the built APK
        generate_release_notes: true # Automatically generate release notes from PRs/commits
